// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6EKesB0NjHvfPbK-XlBx50PHxRvUcoPI',
    appId: '1:732078894918:web:49d367b8152c65a98cbf47',
    messagingSenderId: '732078894918',
    projectId: 'noteplus-ad17a',
    authDomain: 'noteplus-ad17a.firebaseapp.com',
    storageBucket: 'noteplus-ad17a.firebasestorage.app',
    measurementId: 'G-XR5P5TQWWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATykmcX4iR6dydmQgL9EHrvRGe_zQKGMQ',
    appId: '1:732078894918:android:3439e773d209e29a8cbf47',
    messagingSenderId: '732078894918',
    projectId: 'noteplus-ad17a',
    storageBucket: 'noteplus-ad17a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqiWxjUhU1C_XgGOOj_X3lVHkujeS_xy8',
    appId: '1:732078894918:ios:0749744529b4ec228cbf47',
    messagingSenderId: '732078894918',
    projectId: 'noteplus-ad17a',
    storageBucket: 'noteplus-ad17a.firebasestorage.app',
    iosBundleId: 'com.example.noteplusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqiWxjUhU1C_XgGOOj_X3lVHkujeS_xy8',
    appId: '1:732078894918:ios:0749744529b4ec228cbf47',
    messagingSenderId: '732078894918',
    projectId: 'noteplus-ad17a',
    storageBucket: 'noteplus-ad17a.firebasestorage.app',
    iosBundleId: 'com.example.noteplusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6EKesB0NjHvfPbK-XlBx50PHxRvUcoPI',
    appId: '1:732078894918:web:053b367d79671fe48cbf47',
    messagingSenderId: '732078894918',
    projectId: 'noteplus-ad17a',
    authDomain: 'noteplus-ad17a.firebaseapp.com',
    storageBucket: 'noteplus-ad17a.firebasestorage.app',
    measurementId: 'G-0EWFC9VCQK',
  );
}
